version: '2.9'

services:

  keycloak-database:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    container_name: keycloak-database
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-service:
    container_name: keycloak-service
    image: jboss/keycloak:16.1.1
    restart: unless-stopped
    volumes: 
      - ./springbootapp-realm.json:/opt/realm.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-database # name of the container
      DB_DATABASE: keycloak # name of the database
      DB_USER: keycloak # postgres username
      DB_SCHEMA: public
      DB_PASSWORD: password # postgres password
      KEYCLOAK_USER: admin # admin username for keycloak UI
      KEYCLOAK_PASSWORD: strongpassword # admin password for keycloak UI
      KEYCLOAK_IMPORT: /opt/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "8180:8080"
      - "8443:8443"
    depends_on:
      - keycloak-database
    healthcheck:
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/auth/realms/master"
        ]

volumes:
  keycloak-data:
